apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: begbot-dev

resources:
  - ../../services/api
  - ../../services/workers
  - ../../services/frontend

patches:
  - path: replicas.yaml
  - path: env.yaml

images:
  - name: begbot-image
    newTag: dev-latest

commonLabels:
  environment: development
