apiVersion: apps/v1
kind: Deployment
metadata:
  name: begbot-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: begbot-workers
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: begbot-frontend
spec:
  replicas: 1
