apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: begbot-prod

resources:
  - ../../services/api
  - ../../services/workers
  - ../../services/frontend

patches:
  - path: replicas.yaml
  - path: hpa.yaml
  - path: pdb.yaml
  - path: env.yaml

images:
  - name: begbot-image
    newTag: v1.0.0

commonLabels:
  environment: production
