apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - external-secret.yaml

labels:
  - pairs:
      app: begbot

generatorOptions:
  disableNameSuffixHash: true
