apiVersion: v1
kind: Secret
metadata:
  name: begbot-secrets
type: Opaque
stringData:
  DATABASE_HOST: "" # Managed by External Secrets
  DATABASE_PORT: "" # Managed by External Secrets
  DATABASE_USER: "" # Managed by External Secrets
  DATABASE_PASSWORD: "" # Managed by External Secrets
  DATABASE_NAME: "" # Managed by External Secrets
  LLM_API_KEY: "" # Managed by External Secrets
  SMTP_USERNAME: "" # Managed by External Secrets
  SMTP_PASSWORD: "" # Managed by External Secrets
  SMTP_FROM: "" # Managed by External Secrets
