apiVersion: v1
kind: Secret
metadata:
  name: begbot-secrets
  labels:
    app: begbot
type: Opaque
stringData:
  DATABASE_USER: replaceme
  DATABASE_PASSWORD: replaceme
  LLM_API_KEY: replaceme
  SUPABASE_URL: replaceme
  SUPABASE_KEY: replaceme
