apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: begbot-dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: replicas.yaml
    target:
      name: begbot
      kind: Deployment

images:
  - name: ghcr.io/simonbrundin/begbot:latest
    newTag: dev-$(shell git rev-parse --short HEAD 2>/dev/null || echo "latest")
